# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_num', models.IntegerField(default=0)),
                ('prescription', models.TextField(default='')),
                ('result', models.TextField(default='')),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 12, 15, 10, 9, 30, 672046))),
                ('man', models.CharField(default='temp', max_length=10)),
                ('p_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=100)),
                ('sort', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default=' ', max_length=100)),
                ('p_age', models.IntegerField(default='')),
                ('p_number', models.IntegerField(default='')),
                ('p_tel_number', models.IntegerField(default='')),
                ('p_sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=2)),
                ('p_marriage', models.CharField(choices=[('已婚', '已婚'), ('未婚', '未婚')], default=' ', max_length=2)),
                ('p_address', models.CharField(default=' ', max_length=100, null=True)),
                ('p_id_num', models.CharField(default=' ', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_num', models.IntegerField()),
                ('p_number', models.IntegerField()),
                ('man', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_num', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('operator', models.CharField(max_length=100)),
            ],
        ),
    ]
